version: '3'
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5674:5432"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app:
    container_name: aso_books_app
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: prod
      DB_CONNECTION: postgres
      DB_HOST: postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: 5432
      REDIS_PORT: 6379
      REDIS_HOST: redis
      PROJECT_NAME: AsoBooks
      VERSION: 1
      AUTH_SECRET: ${AUTH_SECRET}
      AMAZON_S3_ACCESS_KEY: ${AMAZON_S3_ACCESS_KEY}
      AMAZON_S3_SECRET_KEY: ${AMAZON_S3_SECRET_KEY}
      AMAZON_S3_BUCKET: ${AMAZON_S3_BUCKET}
    depends_on:
      - postgres
      - redis
  worker:
    container_name: aso_books_worker
    build:
      context: .
      dockerfile: worker.Dockerfile
    ports:
      - 4001:4001
    environment:
      PORT: 4001
      NODE_ENV: prod
      DB_CONNECTION: postgres
      DB_HOST: postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: 5432
      REDIS_PORT: 6379
      REDIS_HOST: redis
      PROJECT_NAME: AsoBooks
      EMAIL_PORT: 587
      MAILER_HOST:  ${MAILER_HOST}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - app




